package com.github.kr328.clash.common.sync

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import java.util.Calendar
import java.util.TimeZone
import java.util.zip.ZipEntry
import java.util.zip.ZipInputStream
import java.util.zip.ZipOutputStream

class VergeBackupCodecTest {
    // ---- 夹具:按 verge v2.5.x 备份包格式手工构造 ----

    private val mainConfig = """
        # 订阅内容示例
        proxies:
          - name: 香港 01
            type: ss
            server: example.com
            port: 443
    """.trimIndent().toByteArray()

    private val mergeConfig = """
        # merge 增强内容
        prepend-rules:
          - DOMAIN,example.com,DIRECT
    """.trimIndent().toByteArray()

    private val scriptConfig = "function main(config) {\n  return config;\n}\n".toByteArray()

    private val profilesYamlText = """
        # Profiles Config for Clash Verge
        current: Rtest1234567
        items:
          - uid: Rtest1234567
            type: remote
            name: 测试订阅
            desc: 这是一个测试订阅
            file: Rtest1234567.yaml
            url: https://example.com/sub?token=secret
            home: https://example.com/dashboard
            updated: 1727769600
            selected:
              - name: 节点选择
                now: 香港 01
            extra:
              upload: 1048576
              download: 2097152
              total: 1073741824
              expire: 4102444800
              unknown_extra_field: kept
            option:
              user_agent: clash-verge/v2.5.7
              with_proxy: false
              self_proxy: true
              update_interval: 1440
              timeout_seconds: 30
              danger_accept_invalid_certs: true
              allow_auto_update: true
              merge: mtest1234567
              script: stest1234567
              rules: rtest1234567
              proxies: ptest1234567
              groups: gtest1234567
              unknown_option_field: 42
            unknown_item_field: keep-me
          - uid: mtest1234567
            type: merge
            name: 全局扩展配置
            file: mtest1234567.yaml
          - uid: stest1234567
            type: script
            file: stest1234567.yaml
        some_future_root_field:
          nested: 1
    """.trimIndent() + "\n"

    private fun buildVergePackage(): ByteArray = zipOf(
        linkedMapOf(
            "profiles.yaml" to profilesYamlText.toByteArray(Charsets.UTF_8),
            "profiles/Rtest1234567.yaml" to mainConfig,
            "profiles/mtest1234567.yaml" to mergeConfig,
            "profiles/stest1234567.yaml" to scriptConfig,
            "verge.yaml" to "webdav_url: https://dav.example.com\nwebdav_username: u\nwebdav_password: p\n".toByteArray(),
            "config.yaml" to "# Generated by Clash Verge\nmode: rule\n".toByteArray(),
            "dns_config.yaml" to "enable: true\n".toByteArray(),
            "future-root-file.yaml" to "future: true\n".toByteArray(),
        )
    )

    // ---- 用例 ----

    @Test
    fun `解析 - 订阅名称 URL 更新间隔 流量信息与订阅内容文件正确读出`() {
        val backup = VergeBackupCodec.decode(buildVergePackage())

        assertEquals("Rtest1234567", backup.current)
        assertEquals(3, backup.items.size)

        val remote = backup.items[0]
        assertEquals("Rtest1234567", remote.uid)
        assertEquals("remote", remote.type)
        assertEquals("测试订阅", remote.name)
        assertEquals("这是一个测试订阅", remote.desc)
        assertEquals("Rtest1234567.yaml", remote.file)
        assertEquals("https://example.com/sub?token=secret", remote.url)
        assertEquals("https://example.com/dashboard", remote.home)
        assertEquals(1727769600L, remote.updated)

        val traffic = remote.extra!!
        assertEquals(1048576L, traffic.upload)
        assertEquals(2097152L, traffic.download)
        assertEquals(1073741824L, traffic.total)
        assertEquals(4102444800L, traffic.expire)

        val option = remote.option!!
        assertEquals("clash-verge/v2.5.7", option.userAgent)
        assertEquals(false, option.withProxy)
        assertEquals(true, option.selfProxy)
        assertEquals(1440L, option.updateInterval)
        assertEquals(30L, option.timeoutSeconds)
        assertEquals(true, option.dangerAcceptInvalidCerts)
        assertEquals(true, option.allowAutoUpdate)
        assertEquals("mtest1234567", option.merge)
        assertEquals("stest1234567", option.script)
        assertEquals("rtest1234567", option.rules)
        assertEquals("ptest1234567", option.proxies)
        assertEquals("gtest1234567", option.groups)

        assertArrayEquals(mainConfig, backup.contentFiles["Rtest1234567.yaml"])

        assertEquals("merge", backup.items[1].type)
        assertEquals("script", backup.items[2].type)
    }

    @Test
    fun `编码到解析往返无损`() {
        val first = VergeBackupCodec.decode(buildVergePackage())
        val second = VergeBackupCodec.decode(VergeBackupCodec.encode(first))

        assertBackupsEqual(first, second)
    }

    @Test
    fun `未知条目与未知字段在往返后原样保留`() {
        val original = VergeBackupCodec.decode(buildVergePackage())
        val roundTripped = VergeBackupCodec.decode(VergeBackupCodec.encode(original))

        // profiles.yaml 顶层未知字段
        assertEquals(mapOf("nested" to 1), roundTripped.extraFields["some_future_root_field"])

        val remote = roundTripped.items[0]
        // 条目级未知字段与未建模字段(selected 节点选择)原样保留
        assertEquals("keep-me", remote.extraFields["unknown_item_field"])
        assertEquals(
            listOf(mapOf("name" to "节点选择", "now" to "香港 01")),
            remote.extraFields["selected"],
        )
        // option 级未知字段
        assertEquals(42, remote.option!!.extraFields["unknown_option_field"])
        // extra 级未知字段
        assertEquals("kept", remote.extra!!.extraFields["unknown_extra_field"])

        // 增强文件条目与其内容文件原样保留
        assertEquals("merge", roundTripped.items[1].type)
        assertEquals("全局扩展配置", roundTripped.items[1].name)
        assertEquals("mtest1234567.yaml", roundTripped.items[1].file)
        assertArrayEquals(mergeConfig, roundTripped.contentFiles["mtest1234567.yaml"])
        assertArrayEquals(scriptConfig, roundTripped.contentFiles["stest1234567.yaml"])

        // zip 根部未知文件原样保留
        assertArrayEquals("future: true\n".toByteArray(), roundTripped.extraFiles["future-root-file.yaml"])
    }

    @Test
    fun `生成的包不含 verge 设置文件`() {
        val backup = VergeBackupCodec.decode(buildVergePackage())
        val names = zipEntryNames(VergeBackupCodec.encode(backup))

        assertFalse("verge.yaml" in names)
        assertFalse("config.yaml" in names)
        assertFalse("dns_config.yaml" in names)
        assertTrue("profiles.yaml" in names)
        assertTrue("profiles/Rtest1234567.yaml" in names)
        assertTrue("profiles/mtest1234567.yaml" in names)
        assertTrue("profiles/stest1234567.yaml" in names)
        assertTrue("future-root-file.yaml" in names)
    }

    @Test
    fun `生成文件名符合 android-backup 时间戳约定`() {
        // 非 UTC 时区,验证文件名取的是该时区的本地时间
        val zone = TimeZone.getTimeZone("Asia/Shanghai")
        val calendar = Calendar.getInstance(zone)
        calendar.clear()
        calendar.set(2026, Calendar.OCTOBER, 1, 18, 58, 24)

        assertEquals(
            "android-backup-2026-10-01_18-58-24.zip",
            VergeBackupCodec.backupFileName(calendar.timeInMillis, zone),
        )
    }

    @Test
    fun `生成的 profiles_yaml 保留 verge 头注释`() {
        val backup = VergeBackupCodec.decode(buildVergePackage())
        val encoded = VergeBackupCodec.encode(backup)
        val yaml = String(zipEntry(encoded, "profiles.yaml")!!, Charsets.UTF_8)

        assertTrue(yaml.startsWith("# Profiles Config for Clash Verge"))
    }

    @Test(expected = IllegalArgumentException::class)
    fun `缺少 profiles_yaml 时快速失败`() {
        VergeBackupCodec.decode(zipOf(mapOf("verge.yaml" to "x: 1\n".toByteArray())))
    }

    // ---- 辅助 ----

    private fun assertBackupsEqual(expected: VergeBackup, actual: VergeBackup) {
        assertEquals(expected.current, actual.current)
        assertEquals(expected.items, actual.items)
        assertEquals(expected.extraFields, actual.extraFields)
        assertEquals(expected.contentFiles.keys, actual.contentFiles.keys)
        assertEquals(expected.extraFiles.keys, actual.extraFiles.keys)
        expected.contentFiles.forEach { (name, data) -> assertArrayEquals(data, actual.contentFiles[name]) }
        expected.extraFiles.forEach { (name, data) -> assertArrayEquals(data, actual.extraFiles[name]) }
    }

    private fun zipOf(entries: Map<String, ByteArray>): ByteArray {
        val out = ByteArrayOutputStream()
        ZipOutputStream(out).use { zip ->
            for ((name, data) in entries) {
                zip.putNextEntry(ZipEntry(name))
                zip.write(data)
                zip.closeEntry()
            }
        }
        return out.toByteArray()
    }

    private fun zipEntryNames(zip: ByteArray): List<String> {
        val names = ArrayList<String>()
        ZipInputStream(ByteArrayInputStream(zip)).use { stream ->
            while (true) {
                val entry = stream.nextEntry ?: break
                if (!entry.isDirectory) names.add(entry.name)
            }
        }
        return names
    }

    private fun zipEntry(zip: ByteArray, name: String): ByteArray? {
        ZipInputStream(ByteArrayInputStream(zip)).use { stream ->
            while (true) {
                val entry = stream.nextEntry ?: return null
                if (entry.name == name) return stream.readBytes()
            }
            @Suppress("UNREACHABLE_CODE")
            return null
        }
    }
}
